### ISSUE TITLE
iOS12 自动填写  提示文字是英文的。。有没有办法跟着系统改变？

### ISSUE THREAD

**Issue by liubang0909** [wgy6055/WGDigitField#1]
代码写的很棒。。 学到很多。。UITextContentTypeOneTimeCode   UITextInput  非常感谢分享。但是有个小问题。。提示文字是英文的  有没有办法跟着系统改变？变成中文的。。

**Comment by liubang0909** [comment]
![ded3250a452e8b961193c918b12671e4](https://user-images.githubusercontent.com/12213692/48903968-ef79a800-ee97-11e8-82f5-60bbc6f79e30.png)

**Comment by wgy6055** [comment]
个人感觉应该是跟系统相关的吧？我抽空验证一下

**Comment by wgy6055** [comment]
我原本以为在 `info.plist` 文件中加上 `CFBundleAllowMixedLocalizations = true` 就可以解决问题了，但是并没有，因为感觉这个问题就是 APP 没有获取到系统的 Locale 导致的。目前还没有找到解决办法。

**Comment by wgy6055** [comment]
找到问题所在了。

因为我在 iOS 10 以上使用了 `UIKeyboardTypeASCIICapableNumberPad` ，最初使用这个 `keyboardType` 的原因是：有的语言（比如北印度语 Hindi）使用的数字并非阿拉伯数字（也就是 ASCII 码不支持的），为了防止用户输入非 ASCII 的数字，所以使用了这个类型。看来这个类型并不支持本地化的自动填充提示。

改成 `UIKeyboardTypeNumberPad` 以后问题就解决了，而且阿拉伯数字的准入校验在 `WGDigitView` 中已经做过了，所以也就没必要再使用 `UIKeyboardTypeASCIICapableNumberPad` 了。
https://github.com/wgy6055/WGDigitField/blob/348f1611fca27238f721ba08a8192fa1cdcd1c73/WGDigitField/Classes/WGDigitView.m#L51

**Comment by liubang0909** [comment]
好的  谢谢🙏。差点向内部还有textfield的“恶势力低头”。。 再次感谢

**Comment by wodeyishuiliunian** [comment]
我的还是英文，不知道为什么

**Comment by wgy6055** [comment]
> 我的还是英文，不知道为什么

系统偏好语言设置的是中文吗？
